/**
 * Catalog API
 * This is a API to fetch and order catalog items from different cloud sources
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CollectionLinks from './CollectionLinks';
import CollectionMetadata from './CollectionMetadata';
import OrderItem from './OrderItem';

/**
 * The OrderItemsCollection model module.
 * @module model/OrderItemsCollection
 * @version 0.1.0
 */
class OrderItemsCollection {
    /**
     * Constructs a new <code>OrderItemsCollection</code>.
     * @alias module:model/OrderItemsCollection
     */
    constructor() { 
        
        OrderItemsCollection.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OrderItemsCollection</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrderItemsCollection} obj Optional instance to populate.
     * @return {module:model/OrderItemsCollection} The populated <code>OrderItemsCollection</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderItemsCollection();

            if (data.hasOwnProperty('meta')) {
                obj['meta'] = CollectionMetadata.constructFromObject(data['meta']);
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = CollectionLinks.constructFromObject(data['links']);
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [OrderItem]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/CollectionMetadata} meta
 */
OrderItemsCollection.prototype['meta'] = undefined;

/**
 * @member {module:model/CollectionLinks} links
 */
OrderItemsCollection.prototype['links'] = undefined;

/**
 * @member {Array.<module:model/OrderItem>} data
 */
OrderItemsCollection.prototype['data'] = undefined;






export default OrderItemsCollection;

