/**
 * Catalog API
 * This is a API to fetch and order catalog items from different cloud sources
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProgressMessage model module.
 * @module model/ProgressMessage
 * @version 0.1.0
 */
class ProgressMessage {
    /**
     * Constructs a new <code>ProgressMessage</code>.
     * @alias module:model/ProgressMessage
     */
    constructor() { 
        
        ProgressMessage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProgressMessage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProgressMessage} obj Optional instance to populate.
     * @return {module:model/ProgressMessage} The populated <code>ProgressMessage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProgressMessage();

            if (data.hasOwnProperty('received_at')) {
                obj['received_at'] = ApiClient.convertToType(data['received_at'], 'Date');
            }
            if (data.hasOwnProperty('level')) {
                obj['level'] = ApiClient.convertToType(data['level'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('order_item_id')) {
                obj['order_item_id'] = ApiClient.convertToType(data['order_item_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Date} received_at
 */
ProgressMessage.prototype['received_at'] = undefined;

/**
 * @member {module:model/ProgressMessage.LevelEnum} level
 */
ProgressMessage.prototype['level'] = undefined;

/**
 * @member {String} message
 */
ProgressMessage.prototype['message'] = undefined;

/**
 * @member {String} order_item_id
 */
ProgressMessage.prototype['order_item_id'] = undefined;





/**
 * Allowed values for the <code>level</code> property.
 * @enum {String}
 * @readonly
 */
ProgressMessage['LevelEnum'] = {

    /**
     * value: "info"
     * @const
     */
    "info": "info",

    /**
     * value: "error"
     * @const
     */
    "error": "error",

    /**
     * value: "warning"
     * @const
     */
    "warning": "warning",

    /**
     * value: "debug"
     * @const
     */
    "debug": "debug"
};



export default ProgressMessage;

