/**
 * Catalog API
 * This is a API to fetch and order catalog items from different cloud sources
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProviderControlParameters model module.
 * @module model/ProviderControlParameters
 * @version 0.1.0
 */
class ProviderControlParameters {
    /**
     * Constructs a new <code>ProviderControlParameters</code>.
     * JSON Schema for Provider control parameters
     * @alias module:model/ProviderControlParameters
     */
    constructor() { 
        
        ProviderControlParameters.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProviderControlParameters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProviderControlParameters} obj Optional instance to populate.
     * @return {module:model/ProviderControlParameters} The populated <code>ProviderControlParameters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProviderControlParameters();

        }
        return obj;
    }


}






export default ProviderControlParameters;

