/**
 * Catalog API
 * This API gets and orders catalog items from different cloud sources.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ShareInfo model module.
 * @module model/ShareInfo
 * @version 0.1.0
 */
class ShareInfo {
    /**
     * Constructs a new <code>ShareInfo</code>.
     * @alias module:model/ShareInfo
     */
    constructor() { 
        
        ShareInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ShareInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ShareInfo} obj Optional instance to populate.
     * @return {module:model/ShareInfo} The populated <code>ShareInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ShareInfo();

            if (data.hasOwnProperty('group_uuid')) {
                obj['group_uuid'] = ApiClient.convertToType(data['group_uuid'], 'String');
            }
            if (data.hasOwnProperty('group_name')) {
                obj['group_name'] = ApiClient.convertToType(data['group_name'], 'String');
            }
            if (data.hasOwnProperty('permissions')) {
                obj['permissions'] = ApiClient.convertToType(data['permissions'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * The Group UUID
 * @member {String} group_uuid
 */
ShareInfo.prototype['group_uuid'] = undefined;

/**
 * The Group Name
 * @member {String} group_name
 */
ShareInfo.prototype['group_name'] = undefined;

/**
 * One or more permissions currently applied to this group.
 * @member {Array.<String>} permissions
 */
ShareInfo.prototype['permissions'] = undefined;






export default ShareInfo;

