/**
 * Catalog API
 * This API gets and orders catalog items from different cloud sources.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SharePolicy model module.
 * @module model/SharePolicy
 * @version 0.1.0
 */
class SharePolicy {
    /**
     * Constructs a new <code>SharePolicy</code>.
     * @alias module:model/SharePolicy
     * @param permissions {Array.<String>} The permissions to apply for this share.
     * @param groupUuids {Array.<String>} An array of group UUID's retrieved from the RBAC Service with whom the resource has to be shared.
     */
    constructor(permissions, groupUuids) { 
        
        SharePolicy.initialize(this, permissions, groupUuids);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, permissions, groupUuids) { 
        obj['permissions'] = permissions;
        obj['group_uuids'] = groupUuids;
    }

    /**
     * Constructs a <code>SharePolicy</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SharePolicy} obj Optional instance to populate.
     * @return {module:model/SharePolicy} The populated <code>SharePolicy</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SharePolicy();

            if (data.hasOwnProperty('permissions')) {
                obj['permissions'] = ApiClient.convertToType(data['permissions'], ['String']);
            }
            if (data.hasOwnProperty('group_uuids')) {
                obj['group_uuids'] = ApiClient.convertToType(data['group_uuids'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * The permissions to apply for this share.
 * @member {Array.<String>} permissions
 */
SharePolicy.prototype['permissions'] = undefined;

/**
 * An array of group UUID's retrieved from the RBAC Service with whom the resource has to be shared.
 * @member {Array.<String>} group_uuids
 */
SharePolicy.prototype['group_uuids'] = undefined;






export default SharePolicy;

